apiVersion: apps/v1
kind: Deployment
metadata: #removed incorrect indentation
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}/nginx:{{ .Values.image.tag }}
        name: {{ .Release.Name }}
        ports:
        - containerPort: 80
        imagePullPolicy: {{ .Values.image.pullPolicy }}
